### PR TITLE
Ignore .size-snapshot.json

### PR DESCRIPTION
**Pull request by mikl**
This file is created by `tsdx watch`, and should probably not be tracked in git.

### CODE REVIEW

**Comment by erikras** [comment]
It's tracked in [Formik](https://github.com/jaredpalmer/formik/blob/master/.size-snapshot.json).

**Comment by mikl** [comment]
It might be worth tracking, but the one I get contains absolute paths (which will cause problems when multiple devs work on it), so I guess Formik has that configured differently, somehow?

Mine looks like:
```
{
  "/Users/mikl/Work/Node.js/edzif-validator/dist/edzif-validator.cjs.development.js": {
    "bundled": 125,
    "minified": 72,
    "gzipped": 86
  },
  "/Users/mikl/Work/Node.js/edzif-validator/dist/edzif-validator.cjs.production.js": {
    "bundled": 81,
    "minified": 50,
    "gzipped": 66
  },
  "/Users/mikl/Work/Node.js/edzif-validator/dist/edzif-validator.es.production.js": {
    "bundled": 63,
    "minified": 33,
    "gzipped": 52,
    "treeshaked": {
      "rollup": {
        "code": 0,
        "import_statements": 0
      },
      "webpack": {
        "code": 951
      }
    }
  },
  "/Users/mikl/Work/Node.js/edzif-validator/dist/edzif-validator.umd.development.js": {
    "bundled": 436,
    "minified": 250,
    "gzipped": 188
  },
  "/Users/mikl/Work/Node.js/edzif-validator/dist/edzif-validator.umd.production.js": {
    "bundled": 386,
    "minified": 228,
    "gzipped": 175
  }
}
```

**Comment by jaredpalmer** [comment]
@TrySound should this be tracked?

**Comment by TrySound** [comment]
It should be commited. @mikl Looks like a bug. I didn't see it before. Could you rise an issue in rollup-plugin-size-snapshot?

**Comment by TrySound** [comment]
@jaredpalmer I get it. tsdx passes resolved paths to output. And size snapshot put them without processing. Is it possible to pass relative paths to rollup config?

**Comment by jaredpalmer** [comment]
Probably.

**Comment by jaredpalmer** [comment]
Duplicate. Closing.

**Comment by TrySound** [comment]
@jaredpalmer I fixed this problem in rollup-plugin-size-snapshot v0.9

**Pull request closed without merging**
